include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    constant_identifier_names: false
    depend_on_referenced_packages: false
    prefer_const_constructors: false
    prefer_single_quotes: true
